repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgres
    namespace: storage
    createNamespace: true
    chart: bitnami/postgresql
    values:
      - values.yaml
