apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: smart-home
  labels:
    app: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.9
  selector:
    app: mosquitto
  ports:
  - port: 1883
    name: mqtt
