apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql-operator

helmCharts:
  - name: mysql-operator
    repo: https://mysql.github.io/mysql-operator/
    releaseName: mysql-operator
    namespace: mysql-operator
    version: 2.2.2
    includeCRDs: true
    valuesFile: values.yaml
