apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fasten-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fasten-secrets
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: kv/fasten
        property: jwt_secret
