apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fasten-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: fasten-secrets
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: kv/fasten
        property: jwt_secret
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fasten
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: "fasten"
  serviceName: "fasten"
  replicas: 1
  template:
    metadata:
      labels:
        app: fasten
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: docker-reg
      containers:
        - name: fasten
          image: ghcr.io/fastenhealth/fasten-onprem:main-v1.1.2
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 8Gi
            limits:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 8Gi
          env:
            - name: AUTHENTICATION_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fasten-secrets
                  key: jwt-secret
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: fasten-db
              mountPath: /opt/fasten/db
            - name: fasten-cache
              mountPath: /opt/fasten/cache
  volumeClaimTemplates:
    - metadata:
        name: fasten-db
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 32Gi
    - metadata:
        name: fasten-cache
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fasten-svc
  namespace: homelab
  labels:
    app: fasten
spec:
  ports:
    - port: 8080
      name: web
  selector:
    app: fasten
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fasten-ingress
  namespace: homelab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &fastenHost fasten.mcmumf.dev
      secretName: fasten-cert
  rules:
    - host: *fastenHost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fasten-svc
                port:
                  number: 8080
