apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sidequests-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sidequests-secrets
  data:
    - secretKey: admin-user
      remoteRef:
        key: kv/sidequests
        property: admin-user
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: admin-password
      remoteRef:
        key: kv/sidequests
        property: admin-password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: secret-key
      remoteRef:
        key: kv/sidequests
        property: secret-key
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
