apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sidequests-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sidequests-secrets
  data:
    - secretKey: admin-user
      remoteRef:
        key: kv/sidequests
        property: admin-user

    - secretKey: admin-password
      remoteRef:
        key: kv/sidequests
        property: admin-password

    - secretKey: secret-key
      remoteRef:
        key: kv/sidequests
        property: secret-key
