controller:
  allowSnippetAnnotations: true
  admissionWebhooks:
    patch:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
  ingressClassResource:
    name: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx"
  config:
    enable-real-ip: true
    forwarded-for-header: proxy_protocol
    ssl-protocols: "TLSv1.2 TLSv1.3"
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.5.6
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      effect: "NoSchedule"
