controller:
  # kind: DaemonSet
  allowSnippetAnnotations: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  minAvailable: 2
  admissionWebhooks:
    patch:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  config:
    enable-real-ip: true
    forwarded-for-header: proxy_protocol
    use-forwarded-headers: true
    ssl-protocols: "TLSv1.2 TLSv1.3"
  service:
    externalTrafficPolicy: Cluster
    loadBalancerIP: 192.168.5.6
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      effect: "NoSchedule"
