apiVersion: v1
kind: Service
metadata:
  name: minecraft-vanilla-lb
  namespace: games
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.7
  selector:
    app: minecraft-vanilla-minecraft
  ports:
    - name: minecraft-vanilla
      protocol: TCP
      port: 25565
