toolbox:
  enabled: true
monitoring:
  enabled: true
  createPrometheusRules: true
configOverride: |
  [global]
  bdev_enable_discard = true
  bdev_async_discard = true
  osd_class_update_on_start = false
network:
  provider: host
  connections:
    encryption:
      enabled: true
    compression:
      enabled: true
cephClusterSpec:
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    urlPrefix: /
    ssl: false
ingress:
  dashboard:
    ingressClassName: ""
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    host:
      name: &host "rook.mcmumf.dev"
      path: "/"
    tls:
      - hosts:
          - *host
storage:
  useAllNodes: false
  useAllDevices: false
  config:
    odsPerDevice: "1"
  nodes:
    - name: "hl1"
      devices:
        - name: ""
cephBlockPools:
  - name: ceph-blockpool
    spec:
      failureDomain: host
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
cephFileSystems:
  - name: ceph-filesystem
