apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

<<<<<<< Updated upstream
helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: 0.15.4
    releaseName: rook-ceph
    namespace: rook-ceph
    includeCRDs: true
    valuesFile: values.yaml
=======
namespace: rook-ceph

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    releaseName: rook-ceph
    namespace: rook-ceph
    version: v1.15.4
    valuesFile: rook-values.yaml
    includeCRDs: true
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    version: v1.15.4
    valuesFile: cluster-values.yaml
    includeCRDs: true
>>>>>>> Stashed changes
