apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    releaseName: rook-ceph
    namespace: rook-ceph
    version: v1.16.1
    valuesFile: rook-values.yaml
    includeCRDs: true
  # - name: rook-ceph-cluster
  #   repo: https://charts.rook.io/release
  #   releaseName: rook-ceph-cluster
  #   namespace: rook-ceph
  #   version: v1.15.4
  #   valuesFile: cluster-values.yaml
  #   includeCRDs: true
