crds:
  enabled: true
toolbox:
  enabled: true
csi:
  kubeletDirPath: /var/lib/kubelet
  enableCSIHostNetwork: true
  cephFSKernelMountOptions: ms_mode=prefer-crc
  enableLiveness: true
  serviceMonitor:
    enabled: true
  pluginTolerations:
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"
monitoring:
  enabled: true
resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 1100m
    memory: 300Mi
