apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scanservjs-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.org/client-max-body-size: "10g"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_http_version 1.1;
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &host scanner.mcmumf.dev
      secretName: scanservjs-cert
  rules:
    - host: *host
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: scanservjs
              port:
                number: 8080
