apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scanservjs-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &host scanner.mcmumf.dev
      secretName: scanservjs-cert
  rules:
    - host: *host
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: scanservjs
              port:
                number: 8080
