apiVersion: v1
kind: Service
metadata:
  name: scanservjs
  namespace: apps
  labels:
    app: scanservjs
spec:
  selector:
    app: scanservjs
  type: LoadBalancer
  externalIp: 192.168.5.11
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

