apiVersion: v1
kind: Service
metadata:
  name: scanservjs
  namespace: apps
spec:
  selector:
    app: scanservjs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

