apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mealie
  name: mealie-nltk
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
