{{ if .Values.secrets.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-postgres-secrets
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: kv/immich
        property: postgres_user

    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/immich
        property: postgres_password
{{ end }}
