replicas: 1

# Image settings
image:
  # Repository for the Home Assistant image
  repository: standardnotes/server
  # Image pull policy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Override the default name of the Helm chart
nameOverride: ""
# Override the default full name of the Helm chart
fullnameOverride: ""

resources:
  limits: {}
  requests:
    cpu: 1000m
    memory: 2Gi

service:
  ports:
    - 3000
    - 3125

persistence:
  enabled: true

env:
  - name: MODE
    value: self-hosted
  # DB
  - name: DB_HOST
    value: db
  - name: DB_PORT
    value: 3306
  - name: DB_USERNAME
    value: std_notes_user
  - name: DB_PASSWORD
    value: changeme123
  - name: DB_DATABASE
    value: standard_notes_db
  - name: DB_TYPE
    value: mysql
  - name: DB_MIGRATIONS_PATH
    value: dist/migrations/*.js
  # Cache
  - name: REDIS_PORT
    value: 6379
  - name: REDIS_HOST
    value: cache
  - name: CACHE_TYPE
    value: redis
  # Ports
  - name: SYNCING_SERVER_PORT
    value: 3101
  - name: SYNCING_SERVER_GRPC_PORT
    value: 50052
  - name: AUTH_SERVER_PORT
    value: 3103
  - name: AUTH_SERVER_GRPC_PORT
    value: 50051
  - name: FILES_SERVER_PORT
    value: 3104
  - name: REVISIONS_SERVER_PORT
    value: 3105
  # Shared
  - name: AUTH_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: auth-jwt-secret
  - name: VALET_TOKEN_SECRET
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: valet-token-secret
  # Auth
  - name: AUTH_SERVER_LOG_LEVEL
    value: info
  - name: AUTH_SERVER_NODE_ENV
    value: production
  - name: AUTH_SERVER_VERSION
    value: local
  - name: AUTH_SERVER_AUTH_JWT_TTL
    value: 60000
  - name: AUTH_SERVER_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: auth-jwt-secret
  - name: AUTH_SERVER_LEGACY_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: legacy-jwt-secret
  - name: AUTH_SERVER_DISABLE_USER_REGISTRATION
    value: false
  - name: AUTH_SERVER_PSEUDO_KEY_PARAMS_KEY
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: pseudo-key-params-key
  - name: AUTH_SERVER_ACCESS_TOKEN_AGE
    value: 5184000
  - name: AUTH_SERVER_REFRESH_TOKEN_AGE
    value: 31556926
  - name: AUTH_SERVER_MAX_LOGIN_ATTEMPTS
    value: 6
  - name: AUTH_SERVER_FAILED_LOGIN_LOCKOUT
    value: 3600
  - name: AUTH_SERVER_EPHEMERAL_SESSION_AGEAUTH_SERVER_SYNCING_SERVER_URL
    value: 259200
  - name: AUTH_SERVER_ENCRYPTION_SERVER_KEY
    valueFrom:
      secretKeyRef:
        name: standardnotes
        key: encryption-server-key
  - name: AUTH_SERVER_SYNCING_SERVER_URL
    value: http://localhost:3101
  # File Uploads
  - name: AUTH_SERVER_VALET_TOKEN_TTL
    value: 7200
  # Localstack Setup

  # U2F Setup

  # Syncing Server

  # Files Server

  # Revisions Server

  # API Gateway
