apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dns-secrets
  namespace: dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dns-secrets
  data:
    - secretKey: password
      remoteRef:
        key: kv/pihole
        property: pihole_password
