---
- name: Add k8s APT GPG key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add k8s apt repo
  # This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
  shell: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ K8S_VERSION }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"

- name: Update to get k8s packages
  apt:
    update_cache: yes

- name: Install kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold k8s packages
  become: true
  ansible.builtin.dpkg_selections:
    name:
      - kubelet
      - kubeadm
      - kubectl
    selection: hold

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Disable swappiness and pass bridged IPv4 traffic to iptable's chains
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: "vm.swappiness", value: "0" }

- name: Create service drop-in directory
  file:
    path: /etc/systemd/system/kubelet.service.d/
    state: directory
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755

- name: Copy kubeadm conf to drop-in directory
  template: src=20-extra-args.conf.j2 dest=/etc/systemd/system/kubelet.service.d/20-extra-args.conf

- name: Reload kubelet daemon
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
