# Intel GPU Support
- name: Install Intel GPU Packages
  ansible.builtin.apt:
    pkg:
      - firmware-misc-nonfree
      - vainfo
      - mesa-utils
      - intel-opencl-icd
    state: latest

- name: Add i915 Config
  ansible.builtin.copy:
    src: i915.conf
    dest: /etc/modprobe.d/i915.conf
    mode: "0644"

- name: Replace HuC/GuC Files for i915
  ansible.builtin.git:
    repo: "git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git"
    dest: /tmp/linux-firmware

- name: Copy HuC
  ansible.builtin.command: cp /tmp/linux-firmware/i915/dg2_huc_gsc.bin /lib/firmware/i915/dg2_huc_gsc.bin
