---
- name: Enforce minimum Ansible version
  ansible.builtin.assert:
    that:
      - ansible_version.full is version('2.14', '>=')
    msg: "Minimum ansible-core version required is 2.14"

- name: Set Time Zone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Etc/UTC")

# Add debian backports repository
- name: Add modified sources.list
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"
  become: true

- name: Bridge Network Traffic
  include_tasks: bridged-traffic.yaml

- name: Install Extra File Store Dependencies
  apt:
    name:
      - parted
      - open-iscsi
      - nfs-common
      - jq
    state: latest
    update_cache: yes

# Upgrade everything to latest (use full upgrade)
- name: Upgrade packages to the latest version
  apt:
    upgrade: full
    update_cache: yes

- name: Free up disk space
  command: apt clean
  become: true
