apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/McMumf/homelab"
      targetRevision: "talos"
      path: kubernetes/applications/outline
  destination:
    server: https://kubernetes.default.svc
    namespace: outline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
