apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: outline-secrets
  data:
    - secretKey: secret-key
      remoteRef:
        key: apps/outline
        property: secret-key
    - secretKey: utils-secret
      remoteRef:
        key: apps/outline
        property: utils-secret
    - secretKey: aws-access-id
      remoteRef:
        key: apps/outline
        property: aws-access-id
    - secretKey: aws-secret-key
      remoteRef:
        key: apps/outline
        property: aws-secret-key
    - secretKey: db-connection
      remoteRef:
        key: apps/outline
        property: db-connection
    - secretKey: smtp-server
      remoteRef:
        key: apps/outline
        property: smtp-server
    - secretKey: smtp-token
      remoteRef:
        key: apps/outline
        property: smtp-token
    - secretKey: smtp-username
      remoteRef:
        key: apps/outline
        property: smtp-username
    - secretKey: oidc-client
      remoteRef:
        key: apps/outline
        property: oidc-client
    - secretKey: oidc-secret
      remoteRef:
        key: apps/outline
        property: oidc-secret
