apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: outline-secrets
  data:
    - secretKey: secret-key
      remoteRef:
        key: apps/outline
        property: secret-key

    - secretKey: utils-secret
      remoteRef:
        key: apps/outline
        property: utils-secret

    - secretKey: smtp-user
      remoteRef:
        key: apps/outline
        property: smtp-username

    - secretKey: smtp-password
      remoteRef:
        key: apps/outline
        property: smtp-token

    - secretKey: smtp-server
      remoteRef:
        key: apps/outline
        property: smtp-server
