apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-ingress
  namespace: outline
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: outline-app
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - notes.mcmumf.dev
      secretName: notes.mcmumf.dev-tls
  rules:
    - host: notes.mcmumf.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: outline-svc
                port:
                  number: 3000
