apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline

resources:
  - ./db
  - external-secrets.yaml
  - ingress.yaml
  - namespace.yaml
  - ./redis
  - statefulset.yaml
  - service.yaml
