type: postgresql
mode: standalone

fullnameOverride: "outline-cnpg"

version:
  postgresql: "17"

cluster:
  instances: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  storage:
    size: 32Gi
    storageClass: longhorn
  postgresql:
    parameters:
      log_hostname: "off"
      log_timezone: "UTC"
      max_connections: "200"
      shared_buffers: "256MB"
  roles:
    - name: outline
      ensure: present
      comment: Outline User
      login: true
      superuser: true
      inRoles:
        - pg_monitor
        - pg_signal_backend

  initdb:
    database: outline
    owner: outline
    encoding: UTF8

backups:
  enabled: false

poolers:
  - name: pgbouncer
    type: rw
    instances: 1
    parameters:
      max_client_conn: "100"
      default_pool_size: "50"
    template:
      spec:
        containers:
          - name: pgbouncer
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 100Mi
        initContainers:
          - name: bootstrap-controller
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 100Mi
