apiVersion: v1
kind: Service
metadata:
  name: outline-svc
  namespace: apps
  labels:
    app: outline
spec:
  selector:
    app: outline
  ports:
    - port: 3000
      name: web
      targetPort: 3000
      protocol: TCP
  