apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: outline
  namespace: outline
spec:
  selector:
    matchLabels:
      app: outline-app
  replicas: 1
  template:
    metadata:
      labels:
        app: outline-app
    spec:
      containers:
        - name: outline
          image: outlinewiki/outline:0.85.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: web
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 8Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 8Gi
              memory: 1Gi
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: outline-secrets
                  key: secret-key
            - name: UTILS_SECRET
              valueFrom:
                secretKeyRef:
                  name: outline-secrets
                  key: utils-secret
            - name: PORT
              value: "3000"
            - name: COLLABORATION_URL
              value: ""
            - name: URL
              value: "https://notes.mcmumf.dev"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: outline-secrets
                  key: db-connection
            - name: REDIS_URL
              value: "redis://outline-redis:6379"
            # - name: AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: outline-secrets
            #       key: aws-access-id
            # - name: AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: outline-secrets
            #       key: aws-access-id
            # - name: AWS_REGION
            #   value: "us-east-1"
            # - name: AWS_S3_UPLOAD_BUCKET_URL
            #   value: "https://s3.mcmumf.dev"
            # - name: AWS_S3_UPLOAD_BUCKET_NAME
            #   value: "outline"
            # - name: AWS_S3_UPLOAD_MAX_SIZE
            #   value: "26214400"
            # - name: AWS_S3_FORCE_PATH_STYLE
            #   value: "true"
            # - name: AWS_S3_ACL
            #   value: "private"
          volumeMounts:
            - name: outline-data
              mountPath: /var/lib/outline/data
  volumeClaimTemplates:
    - metadata:
        name: outline-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "openebs"
        resources:
          requests:
            storage: 2Gi
