apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: immich-postgres
