apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-postgres-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-postgres
data:
  postgresql.conf: |-
    max_wal_size = 4096
    min_wal_size = 1024
    # and so on
