apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.105.1
          command: ["/bin/sh"]
          args: ["./start-server.sh"]
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_USERNAME
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: MACHINE_LEARNING_HOST
              value: immich-ml
          volumeMounts:
            - name: nfs-volume
              mountPath: /usr/src/app/upload
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:v1.105.1
          # resources:
          #   requests:
          #     gpu.intel.com/i915: 1
          #   limits:
          #     gpu.intel.com/i915: 1
          command: ["/bin/sh"]
          args: ["./start-microservices.sh"]
          ports:
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_USERNAME
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-postgres-secrets
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: DB_HOSTNAME
              value: immich-postgres
          volumeMounts:
            - name: nfs-volume
              mountPath: /usr/src/app/upload
      volumes:
        - name: nfs-volume
          nfs:
            server: 192.168.1.70
            path: /volume1/photos
