apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-server
spec:
  ports:
    - port: 3001
      name: http
  selector:
    app: immich-server
