apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps

resources:
  # - external-secrets.yaml
  - ingress.yaml
  - statefulset.yaml
  - service.yaml

helmCharts:
  - name: mysql-innodbcluster
    repo: https://mysql.github.io/mysql-operator/
    releaseName: ghost-innodb
    namespace: apps
    version: 2.2.2
    valuesFile: ghost-innodb-values.yaml
