apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: "ghost"
  serviceName: "ghost"
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: ghost
          # image: ghost:5.98.1-alpine
          image: ghost:5.98.1 # Use alpine when done messing around
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
              ephemeral-storage: 8Gi
            limits:
              memory: 256Mi
              cpu: 500m
              ephemeral-storage: 8Gi
          env:
            - name: NODE_ENV
              value: "development"
            - name: url
              value: "https://blog.mcmumf.dev"
            # - name: database__client
            #   value: ""
            # - name: database__connection__host
            #   value: ""
            # - name: database__connection__user
            #   value: ""
            # - name: database__connection__password
            #   value: ""
            # - name: database__connection__database
            #   value: ""
            # - name: mail__from
            #   value: "'McMumf's Blog' <blog@mcmumf.dev>"
            # - name: mail__transport
            #   value: "SMTP"
            # - name: mail__options__host
            #   value: ""
            # - name: mail__options__port
            #   value: ""
            # - name: mail__options__secure
            #   value: "true"
            # - name: mail__options__auth__user
            #   value: ""
            # - name: mail__options__auth__pass
            #   value: ""
          ports:
            - containerPort: 2368
              name: web
          volumeMounts:
            - name: ghost-data
              mountPath: /var/lib/ghost/content
  volumeClaimTemplates:
    - metadata:
        name: ghost-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 8Gi
