repositories:
  - name: intel
    url: https://intel.github.io/helm-charts/

releases:
  - name: intel-device-plugins-operator
    namespace: inteldeviceplugins-system
    createNamespace: true
    chart: intel/intel-device-plugins-operator
    version: 0.30.0
