operator:
  env:
    - name: OPERATOR_STS_AUTO_TLS_ENABLED
      value: "off"
    - name: OPERATOR_STS_ENABLED
      value: "on"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      effect: "NoSchedule"
