image:
  repository: getmeili/meilisearch
  tag: v1.46.1
environment:
  MEILI_NO_ANALYTICS: true
  MEILI_ENV: production
auth:
  existingMasterKeySecret: "meilisearch-secrets"

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
