architecture: standalone

auth:
  enabled: false
  existingSecret: n8n-redis-secrets

master:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: openebs

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  configuration: |
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec

service:
  type: ClusterIP
  port: 6379

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
