apiVersion: v1
appVersion: "2024.5"
description: Home Assistant
name: home-assistant
version: 1.0.0
keywords:
- home-assistant
- hass
- hassio
- homeassistant
home: https://github.com/home-assistant/home-assistant
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Home_Assistant_Logo.svg/519px-Home_Assistant_Logo.svg.png
