apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: cnpg-app-cluster
            namespace: apps
          - appName: enclosed
            namespace: apps
          # - appName: fasten
          #   namespace: apps
          # - appName: ghost
          #   namespace: apps
          - appName: homer
            namespace: apps
          # - appName: immich
          #   namespace: immich
          - appName: mealie
            namespace: apps
          - appName: morphos
            namespace: apps
          - appName: paperless
            namespace: apps
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/McMumf/Homelab.git
        path: kubernetes/applications/{{appName}}
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      ignoreDifferences:
        - kind: ExternalSecret
          group: external-secrets.io
          jqPathExpressions:
            - ".spec.data[] | select(.remoteRef) | .remoteRef.conversionStrategy"
            - ".spec.data[] | select(.remoteRef) | .remoteRef.decodingStrategy"
            - ".spec.data[] | select(.remoteRef) | .remoteRef.metadataPolicy"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
