apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-redis-secrets
  namespace: outline
  labels:
    app.kubernetes.io/name: outline-redis
    app.kubernetes.io/instance: outline-redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: outline-redis-secrets
    template:
      data:
        redis-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: apps/outline
        property: redis-password

    - secretKey: username
      remoteRef:
        key: apps/outline
        property: redis-username
