apiVersion: v1
kind: Service
metadata:
  name: outline-redis
  namespace: outline
  labels:
    app: outline-redis
spec:
  type: ClusterIP
  selector:
    app: outline-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
