apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argocd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    namespace: argocd
    version: 7.6.7
    valuesFile: values.yaml
