replicaCount: 1

# Image settings
image:
  # Repository for the Mealie image
  repository: ghcr.io/danielbrendel/hortusfox-web
  # Image pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

statefulset:
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  port:
    host: &hostPortNumber 8080
    container: &containerPortNumber 80
  env:
    - name: APP_LANG
      value: en
    - name: APP_ADMIN_EMAIL
      value: homelab-admin@mcmumf.dev
    - name: APP_ADMIN_PASSWORD
      value: test
    - name: DB_CHARSET
      value: utf8mb4
    - name: DB_DATABASE
      value: hortusfox
    - name: DB_HOST
      value: hortusfox-mariadb.homelab.svc.cluster.local
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: hortusfox-secrets
          key: mariadb-password
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: root
  volumeClaimTemplate:
    size: 8Gi
    imagesSize: 4Gi
    logsSize: 1Gi
    backupsSize: 4Gi
    themesSize: 1Gi
    migrateSize: 2Gi

service:
  name: web
  port: *hostPortNumber
  target: *containerPortNumber

ingress:
  tls:
    enabled: true
  host: plants.mcmumf.dev
