---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - { role: crio, tags: crio }

- hosts: master
  gather_facts: true
  become: true
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: worker
  gather_facts: true
  become: true
  roles:
    - { role: kubernetes/worker, tags: worker }

- hosts: master
  gather_facts: true
  become: true
  tasks:
    - name: "MetalLB role"
      include_role:
        name: metallb
      when: "additional_features.metallb"
      run_once: true
      tags: metallb
