apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-postgres-secrets
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: kv/karakeep
        property: nextauth

    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: kv/karakeep
        property: meili-master

    - secretKey: NEXT_PUBLIC_SECRET
      remoteRef:
        key: kv/karakeep
        property: next-public
