# Image settings
image:
  # Repository for the Mealie image
  repository: hkotel/mealie:latest
  # Image pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

statefulset:
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
      ephemeral-storage: 8Gi
    limits:
      memory: 8Gi
      cpu: 2000m
      ephemeral-storage: 8Gi
  port:
    web: 80
  env:
    # General Configs
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: BASE_URL
      value: "https://recipes.mcmumf.dev"
    - name: TOKEN_TIME
      valuue: "24"
    - name: TZ
      value: "UTC"
    - name: ALLOW_SIGNUP
      value: "False"
    # Security Configs
    - name: SECURITY_MAX_LOGIN_ATTEMPTS
      value: "5"
    - name: SECURITY_USER_LOCKOUT_TIME
      value: "24"
    # LDAP Configs
    # - name: LDAP_AUTH_ENABLED
    #   value: "True"
    # - name: LDAP_SERVER_URL
    #   value: "ldap://ldap.mcmumf.dev"
    # - name: LDAP_BIND_TEMPLATE
    #   value: "cn={},ou=users,dc=mcmumf,dc=dev"
    # Web Worker Configs
    - name: MAX_WORKERS
      value: "10"
    - name: WEB_CONCURRENCY
      value: "2"
    # Database Settings
    - name: DB_ENGINE
      value: postgres
    - name: POSTGRES_USER
      value: mealie
    - name: POSTGRES_PASSWORD
      value: test
    - name: POSTGRES_SERVER
      value: postgres-postgresql.storage.svc.cluster.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DB
      value: mealie
  volumeClaimTemplate:
    size: 8Gi

service:
  port: 9000

ingress:
  host: recipes.mcmumf.dev
  tls:
    enabled: false
