apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hassio-proxy-service
  namespace: homelab
  labels:
    kubernetes.io/service-name: hassio-proxy-service # Must be present for EndpointSlice and equal to Service name for automatic mapping - with having it in place, you can change the name of EndpointSlice to something else. The official convention is using Service name as the prefix.
addressType: IPv4
ports:
  - port: 8123
endpoints:
  - addresses:
      - "192.168.1.98" # IP address of your external service that you would like to proxy requests to
---
apiVersion: v1
kind: Service
metadata:
  name: hassio-proxy-service
  namespace: homelab
spec:
  ports:
    - port: 8123
      name: homeassistant
      protocol: TCP
      targetPort: 8123
  type: ClusterIP
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - ha.mcmumf.dev
  #     secretName: ha-ingress
  rules:
    - host: ha.mcmumf.dev
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: hassio-proxy-service
                port:
                  number: 8123
