apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: 0.16.4
    releaseName: node-feature-discovery
    namespace: node-feature-discovery
    includeCRDs: true
    valuesFile: values.yaml
