apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readeck-role
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: readeck-role
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: apps/readeck
        property: pg_user

    - secretKey: password
      remoteRef:
        key: apps/readeck
        property: pg_pass
