apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readeck
  namespace: apps
spec:
  selector:
    matchLabels:
      app: "readeck"
  serviceName: "readeck"
  replicas: 1
  template:
    metadata:
      labels:
        app: readeck
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: readeck
          image: codeberg.org/readeck/readeck:0.16.0
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
              ephemeral-storage: 8Gi
            limits:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 8Gi
          env:
            - name: READECK_LOG_LEVEL
              value: "debug"
            # - name: READECK_SERVER_HOST
            #   value: "0.0.0.0"
            - name: READECK_USE_X_FORWARDED
              value: "true"
            - name: READECK_ALLOWED_HOSTS
              value: "readeck.mcmumf.dev"
            - name: READECK_DATABASE_SOURCE
              valueFrom:
                secretKeyRef:
                  name: readeck-secrets
                  key: pg_conn
          ports:
            - containerPort: 8000
              name: web
          volumeMounts:
            - name: readeck-data
              mountPath: /readeck
  volumeClaimTemplates:
    - metadata:
        name: readeck-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 32Gi
