apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

resources:
  - scheduled-backup.yaml

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: n8n-cnpg
    namespace: n8n
    version: 0.6.0
    valuesFile: values.yaml
