apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-postgres-secrets
  data:
    - secretKey: DB_DATABASE_NAME
      remoteRef:
        key: kv/immich
        property: postgres_db
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: DB_USERNAME
      remoteRef:
        key: kv/immich
        property: postgres_user
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: DB_PASSWORD
      remoteRef:
        key: kv/immich
        property: postgres_password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
