apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi

resources:
  - external-secret.yaml

helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    releaseName: democratic-csi-iscsi
    version: 0.15.0
    valuesFile: values.yaml
