apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prom-stack
    namespace: monitoring
    version: 75.15.1
    valuesFile: values.yaml
    includeCRDs: true
