apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellystat-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jellystat-secrets
  data:
    - secretKey: pg-user
      remoteRef:
        key: kv/jellystat
        property: pg-user
    - secretKey: pg-password
      remoteRef:
        key: kv/jellystat
        property: pg-password
