apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: 0.15.4
    releaseName: rook-ceph-cluster
    namespace: rook-ceph
    valuesFile: values.yaml
