apiVersion: v1
kind: Service
metadata:
  name: hassio
  namespace: smart-home
  labels: {}
  annotations: {}
spec:
  type: ClusterIP
  selector: {}
  ports:
    - port: 8123
      name: http
      targetPort: http
      protocol: TCP
