apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hassio
  namespace: smart-home
  labels: {}
spec:
  serviceName: hassio
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels: {}
    spec:
      hostNetwork: false
      automountServiceAccountToken: false
      securityContext: {}
      containers:
        - name: hassio
          image: "ghcr.io/home-assistant/home-assistant:2024.9.3"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
              ephemeral-storage: &ephemeralHaStorage 8Gi
            limits:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: *ephemeralHaStorage
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: hassio
              mountPath: /config
            - name: hassio-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
      volumes:
        - name: hassio-config
          configMap:
            name: hassio-config
            items:
              - key: config
                path: config
  volumeClaimTemplates:
    - metadata:
        name: hassio
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 32Gi
