apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-tenant

resources:
  - tenant-ca-cert.yaml
  - tenant-ca-issuer.yaml
  - tenant-certificate.yaml

helmCharts:
  - name: tenant
    repo: https://operator.min.io
    releaseName: minio-operator
    namespace: minio-tenant
    version: 6.0.4
    valuesFile: values.yaml
