apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-ca-certificate
  namespace: minio-tenant
spec:
  isCA: true
  commonName: tenant-ca
  secretName: tenant-ca-tls
  duration: 70128h # 8y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: minio-selfsigned-root
    kind: ClusterIssuer
    group: cert-manager.io
