apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: minio-tenant
spec:
  dnsNames:
    - "minio.minio-tenant"
    - "minio.minio-tenant.svc"
    - "minio.minio-tenant.svc.cluster.local"
    - "*.minio.minio-tenant.svc.cluster.local"
    - "*.hl-minio.minio-tenant.svc.cluster.local"
    - "*.hl-minio-hl.minio-tenant.svc.cluster.local"
  secretName: minio-tenant-tls
  issuerRef:
    name: tenant-ca-issuer
