app:
  timezone: "America/New_York"
  global:
    image:
      tag: 2.4
  persistence:
    enabled: true
    storageClass: "openebs"
    accessModes: ["ReadWriteOnce"]
  axes:
    enabled: true
    failureLimit: 10
    # in minutes
    cooloffTime: 30
    # number of reverse proxies involved
    ipwareProxyCount: 1
    # order of magnitude from last proxy for the real ip
    ipwareMetaPrecedenceOrder: "X_FORWARDED_FOR,REMOTE_ADDR"
  environment:
    - name: SITE_URL
      value: "https://fitness.mcmumf.dev"
    - name: GUNICORN_CMD_ARGS
      value: '--timeout 240 --workers 2 --worker-class gthread --threads 3 --forwarded-allow-ips * --proxy-protocol True --access-logformat=''%(h)s %(l)s %({client-ip}i)s %(l)s %({x-real-ip}i)s %(l)s %({x-forwarded-for}i)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'' --access-logfile - --error-logfile -'

celery:
  enabled: true

ingress:
  enabled: true
  ingressClassName: cilium
  url: fitness.mcmumf.dev
  tls: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: Fitness Tracker
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: https://raw.githubusercontent.com/wger-project/wger/master/wger/core/static/images/logos/logo.png
    gethomepage.dev/name: wger
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=wger-app"

redis:
  enabled: true
  auth:
    enabled: true
  # Additional environment variables (Redis server and Sentinel)
  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis
          key: redis-password
  # Arguments for the container entrypoint process (Redis server)
  args:
    - "--requirepass $(REDIS_PASSWORD)"
  storage:
    persistentVolumeClaimName: wger-redis
    className: openebs
  service:
    serverPort: 6379
