app:
  timezone: "America/New_York"
  global:
    image:
      tag: 2.4
    securityContext:
      seccompProfile:
        type: RuntimeDefault
  persistence:
    enabled: true
    storageClass: "openebs"
    accessModes: ["ReadWriteOnce"]
  axes:
    enabled: true
    failureLimit: 10
    # in minutes
    cooloffTime: 30
    # number of reverse proxies involved
    ipwareProxyCount: 1
    # order of magnitude from last proxy for the real ip
    ipwareMetaPrecedenceOrder: "X_FORWARDED_FOR,REMOTE_ADDR"
  environment:
    - name: SITE_URL
      value: "https://fitness.mcmumf.dev"
    - name: GUNICORN_CMD_ARGS
      value: '--timeout 240 --workers 2 --worker-class gthread --threads 3 --forwarded-allow-ips * --proxy-protocol True --access-logformat=''%(h)s %(l)s %({client-ip}i)s %(l)s %({x-real-ip}i)s %(l)s %({x-forwarded-for}i)s %(l)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'' --access-logfile - --error-logfile -'

celery:
  enabled: true

ingress:
  enabled: true
  ingressClassName: cilium
  url: fitness.mcmumf.dev
  tls: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: Fitness Tracker
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: https://raw.githubusercontent.com/wger-project/wger/master/wger/core/static/images/logos/logo.png
    gethomepage.dev/name: wger
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=wger-app"
    gethomepage.dev/href: "https://fitness.mcmumf.dev"
postgres:
  # Note: keep these variables present as the wger chart uses them for the deployment
  # the superuser and user settings will be saved into a secret
  enabled: true
  # changes to the superuser and userDatabase passwords will update
  # the secret where they are save in
  # the user from the user database will be turned into a superuser
  # some database migration in django requires this
  # otherwise it was not able to create the database
  extraScripts: wger-pg-init
  service:
    port: 5432
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ## Storage parameters
  storage:
    ##  Set persistentVolumenClaimName to reference an existing PVC
    persistentVolumeClaimName:
    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    requestedSize: 8Gi
    ## the storage class name
    className: openebs
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

redis:
  enabled: true
  auth:
    enabled: true
  # Additional environment variables (Redis server and Sentinel)
  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis
          key: redis-password
  # Arguments for the container entrypoint process (Redis server)
  args:
    - "--requirepass $(REDIS_PASSWORD)"
  storage:
    className: openebs
  service:
    serverPort: 6379
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
