apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich-machine-learning
  name: immich-machine-learning
  namespace: apps
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    app: immich-machine-learning
