repositories:
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts

releases:
  - name: cloudflared
    namespace: infrastructure
    createNamespace: true
    chart: cloudflare/cloudflare-tunnel
    values:
      - cloudflare:
          # Cloudflare Account Number
          account: ""
          # The name of the tunnel this instance will serve
          tunnelName: "k8s-tunnel"
          # The ID of the above tunnel.
          tunnelId: ""
          # The secret for the tunnel.
          secret: ""
          # If defined, no secret is created for the credentials, and instead, the secret referenced is used
          secretName: null
          # Define ingress rules for the tunnel. See
          # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
          ingress:
            - hostname: "*.mcmumf.dev"
              service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
              originRequest:
                noTLSVerify: true
