apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: outline

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: fresh-rss-cnpg
    namespace: apps
    version: 0.3.1
    valuesFile: values.yaml
