apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: morphos-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: File converter
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Utilities
    gethomepage.dev/icon: https://raw.githubusercontent.com/danvergara/morphos/refs/heads/main/screenshots/morphos.jpg
    gethomepage.dev/name: Morphos
    gethomepage.dev/pod-selector: "app=morphos"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &host file-converter.mcmumf.dev
      secretName: morphos-cert
  rules:
    - host: *host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: morphos
                port:
                  number: 8080
