apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: media
spec:
  serviceName: "qbittorrent"
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
      automountServiceAccountToken: false
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:4.6.4-r0-ls321
          resources:
            requests:
              cpu: 1
              memory: 500Mi
              ephemeral-storage: 32Gi
            limits:
              cpu: 2
              memory: 4Gi
              ephemeral-storage: 32Gi
          ports:
            - name: ui
              containerPort: 8090
              protocol: TCP
            - name: torrent
              containerPort: 6881
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEBUI_PORT
              value: "8090"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - name: qbittorrent-data
              mountPath: /config
            - name: torrents
              mountPath: /downloads
            - name: homelab-nfs
              mountPath: /mnt/library
      volumes:
        - name: homelab-nfs
          nfs:
            server: 192.168.1.70
            path: /volume1/library
  volumeClaimTemplates:
    - metadata:
        name: qbittorrent-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 32Gi
    - metadata:
        name: torrents
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 256Gi
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8090
      name: ui
    - port: 6811
      name: torrent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &qbittorrentIngress qbittorrent.mcmumf.dev
      secretName: qbittorrent-cert
  rules:
    - host: *qbittorrentIngress
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent
                port:
                  number: 8090
