apiVersion: v1
kind: Service
metadata:
  name: immich-ml
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-ml
spec:
  type: ClusterIP
  ports:
    - port: 3003
      protocol: TCP
  selector:
    app: immich-ml
