apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: media-secret-store
    kind: ClusterSecretStore
  target:
    name: freshrss-secrets
  data:
    - secretKey: admin-email
      remoteRef:
        key: media/freshrss
        property: admin-email
    - secretKey: admin-password
      remoteRef:
        key: media/freshrss
        property: admin-password
    - secretKey: admin-api-password
      remoteRef:
        key: media/freshrss
        property: admin-api-password
    - secretKey: oidc-client-id
      remoteRef:
        key: media/freshrss
        property: oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: media/freshrss
        property: oidc-client-secret
    - secretKey: oidc-client-crypto-key
      remoteRef:
        key: media/freshrss
        property: oidc-client-crypto-key
