apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: authentik
            namespace: authentik
          - appName: cert-manager
            namespace: cert-manager
          - appName: cnpg-operator
            namespace: cnpg-system
          - appName: external-secrets
            namespace: external-secrets
          - appName: ingress-nginx
            namespace: ingress-nginx
          - appName: intel-device-plugins
            namespace: inteldeviceplugins-system
          - appName: longhorn
            namespace: longhorn-system
          - appName: node-feature-discovery
            namespace: node-feature-discovery
          - appName: prometheus-stack
            namespace: monitoring
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/McMumf/Homelab.git
        path: kubernetes/infrastructure/{{appName}}
        targetRevision: homelab-2.0
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
