apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: smart-home
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: authentik
          - appName: external-secrets
          - appName: intel-device-plugins-gpu
          - appName: intel-device-plugins-operator
          - appName: longhorn
          - appName: node-feature-discovery
          - appName: prometheus-stack
          - appName: vault
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: smart-home
      source:
        repoURL: https://github.com/McMumf/Homelab.git
        targetRevision: HEAD
        path: kubernetes/infrastructure/{{appName}}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "smart-home"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
