apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: umami-secrets
  data:
    - secretKey: salt
      remoteRef:
        key: apps/umami
        property: salt
