type: postgresql
mode: standalone

version:
  postgresql: "17"

cluster:
  instances: 3
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "2GB"

backups:
  enabled: false

poolers:
  - name: rw
    type: rw
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: rw
  - name: ro
    type: ro
    instances: 1
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
        relabelings:
          - targetLabel: type
            replacement: ro
