apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: tunnel-credentials
  data:
    - secretKey: credentials.json
      remoteRef:
        key: infrastructure/cloudflare-tunnel
        property: credentials.json
