apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: tunnel-credentials
      remoteRef:
        key: infrastructure/cloudflare-tunnel
        property: credentials.json
