apiVersion: v1
kind: Service
metadata:
  labels:
    app: immich-postgres
  name: immich-postgres
  namespace: apps
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: immich-postgres
