repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: storage
    createNamespace: true
    chart: bitnami/redis
    values:
      - values.yaml
