apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
