apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg-operator
    namespace: cnpg-system
    version: 0.1.0
    valuesFile: values.yaml
