type: postgresql
mode: standalone

fullnameOverride: "cnpg-apps"

version:
  postgresql: "17"

cluster:
  instances: 3
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  postgresql:
    parameters:
      log_hostname: "off"
      log_timezone: "UTC"
      max_connections: "200"
      shared_buffers: "256MB"

backups:
  enabled: false

poolers:
  - name: pgbouncer
    type: rw
    instances: 1
    parameters:
      max_client_conn: "1000"
      default_pool_size: "300"
    template:
      spec:
        containers:
          - name: pgbouncer
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 100Mi
        initContainers:
          - name: bootstrap-controller
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 100Mi
