# Enable bridged traffic
- name: Enable overlay modprobe
  become: true
  community.general.modprobe:
    name: overlay
    state: present

- name: Enable br_netfilter modprobe
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Reload CRI-O daemon
  systemd:
    name: crio
    daemon_reload: yes
    state: started
    enabled: yes

- name: Create /etc/sysctl.d/k8s
  become: true
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s
    state: directory

- name: Iptables - bridge-nf-call
  become: true
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s/conf
    sysctl_set: true
    reload: true

- name: Iptables - bridge-nf-call-ip6
  become: true
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s/conf
    sysctl_set: true
    reload: true

- name: Iptables - ipv4.ip_forward
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s/conf
    sysctl_set: true
    reload: true
