apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: enclosed-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: enclosed-secrets
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: kv/enclosed
        property: jwt-secret
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
