apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: enclosed
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: "enclosed"
  serviceName: "enclosed"
  replicas: 1
  template:
    metadata:
      labels:
        app: enclosed
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: enclosed
          image: corentinth/enclosed:1.6.9-rootless
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 8Gi
            limits:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 8Gi
          env:
            - name: AUTHENTICATION_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: enclosed-secrets
                  key: jwt-secret
          ports:
            - containerPort: 8787
              name: web
          volumeMounts:
            - name: enclosed-data
              mountPath: /app/.data
  volumeClaimTemplates:
    - metadata:
        name: enclosed-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "ceph-block"
        resources:
          requests:
            storage: 8Gi
