apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-pg-secrets
  namespace: n8n
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: backups-secret-store
    kind: ClusterSecretStore
  target:
    name: n8n-postgresql
  data:
    - secretKey: password
      remoteRef:
        key: backups/n8n
        property: pg-password

    - secretKey: postgres-password
      remoteRef:
        key: backups/n8n
        property: pg-password
