apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-secrets
  namespace: n8n
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: backups-secret-store
    kind: ClusterSecretStore
  target:
    name: n8n-encryption
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: backups/n8n
        property: encryption-key
