apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: media
spec:
  serviceName: "sonarr"
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        fsGroup: 25343
      automountServiceAccountToken: false
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.10
          resources:
            requests:
              cpu: 1
              memory: 500Mi
              ephemeral-storage: 32Gi
            limits:
              cpu: 2
              memory: 4Gi
              ephemeral-storage: 32Gi
          ports:
            - name: sonarr-http
              containerPort: 8989
              protocol: TCP
          env:
            - name: PGID
              value: "25343"
          volumeMounts:
            - name: sonarr-data
              mountPath: /config
            - name: homelab-nfs
              mountPath: /tv
      volumes:
        - name: homelab-nfs
          nfs:
            server: 192.168.1.70
            path: /volume1/library/Shows
  volumeClaimTemplates:
    - metadata:
        name: sonarr-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - port: 8989
      name: sonarr-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &sonarrIngress sonarr.mcmumf.dev
      secretName: sonarr-cert
  rules:
    - host: *sonarrIngress
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
