apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - apps-secret-store.yaml
  - infra-secret-store.yaml
  - media-secret-store.yaml
  - networking-secret-store.yaml
  - smart-home-secret-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.10.4
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true
    valuesInline:
      includeCRDs: true
