apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: McMumf's Homelab
    background:
      image: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/talos/assets/background.jpg
      blur: sm
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/

  services.yaml: |
    - Utilities:
        - scanservjs:
            href: https://scanner.mcmumf.dev
            icon: https://raw.githubusercontent.com/sbs20/scanservjs/refs/heads/master/app-ui/src/icons/favicon.ico
            description: Web page to interact with the printer's scanner
        - Enclosed:
            href: https://enclosed.mcmumf.dev
            icon:
            description: Send private and secure notes

    - Homelab:
        - Home-Assistant:
            href: https://hassio.mcmumf.dev
            icon: https://raw.githubusercontent.com/home-assistant/frontend/refs/heads/dev/public/static/icons/favicon-32x32.png
        - Jellyin:
            href: https://jellyfin.mcmumf.dev
            icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/refs/heads/master/branding/SVG/icon-transparent.svg
            description: Movies, Music, TV
        - Mealie:
            href: https://recipes.mcmumf.dev
            icon: https://raw.githubusercontent.com/mealie-recipes/mealie/refs/heads/mealie-next/frontend/static/icons/icon-x64.png
            description: Recipes

    - Operations:
        - Authentik:
            href: https://auth.mcmumf.dev
            icon: https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/web/icons/icon.svg
            description: Account Management
        - ArgoCD:
            href: https://argocd.mcmumf.dev
            icon: https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/argocd/argocd-original.svg
            description: Declarative GitOps CD for Kubernetes
        - Vault:
            href: https://argocd.mcmumf.dev
            icon: https://raw.githubusercontent.com/devicons/devicon/refs/heads/master/icons/vault/vault-original.svg
            description: Secrets management

  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""

