apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: McMumf's Homelab
    background:
      image: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/talos/assets/background.jpg
      blur: sm
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - References:
        - Repo:
            - icon: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/main/assets/logo.png
              href: https://github.com/McMumf/homelab
              description: The repo
        - Homepage:
            - icon: homepage.png
              href: https://gethomepage.dev/
              description: Homepage Documentation

  services.yaml: |
    - Utilities:
        - Enclosed:
            href: https://enclosed.mcmumf.dev
            icon: https://raw.githubusercontent.com/CorentinTh/enclosed/refs/heads/main/packages/app-client/public/favicon-32x32.png
            description: Send private and secure notes
        - Morphos:
            href: https://file-converter.mcmumf.dev
            icon: https://raw.githubusercontent.com/danvergara/morphos/refs/heads/main/screenshots/morphos.jpg
            description: File converter

    - Homelab:
        - Home-Assistant:
            href: https://hassio.mcmumf.dev
            icon: https://raw.githubusercontent.com/home-assistant/frontend/refs/heads/dev/public/static/icons/favicon-32x32.png
            description: Home automation
        - Jellyin:
            href: https://jellyfin.mcmumf.dev
            icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/refs/heads/master/branding/SVG/icon-transparent.svg
            description: Movies, Music, TV
        - Mealie:
            href: https://recipes.mcmumf.dev
            icon: https://raw.githubusercontent.com/mealie-recipes/mealie/refs/heads/mealie-next/frontend/static/icons/icon-x64.png
            description: Recipes

    - Operations:
        - Authentik:
            href: https://auth.mcmumf.dev
            icon: https://raw.githubusercontent.com/goauthentik/authentik/refs/heads/main/web/icons/icon.svg
            description: Account Management
        - NAS:
            href: https://nas.mcmumf.dev
            icon: mdi-nas
            description: Network Attached Storage

  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
