apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: McMumf's Homelab
    background:
      image: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/talos/assets/background.jpg
      blur: sm
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Utilities:
        - scanservjs:
            href: http://192.168.5.11:8080
            icon: https://raw.githubusercontent.com/sbs20/scanservjs/refs/heads/master/app-ui/src/icons/favicon.ico
            description: Web page to interact with the printer's Scanner

    - Media:
        - Jellyin:
            href: https://jellyfin.mcmumf.dev
            description: Movies, Music, TV

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""

