apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: McMumf's Homelab
    background:
      image: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/talos/assets/background.jpg
      blur: sm
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - References:
        - Repo:
            - icon: https://raw.githubusercontent.com/McMumf/homelab/refs/heads/main/assets/logo.png
              href: https://github.com/McMumf/homelab
              description: The repo
        - Homepage:
            - icon: homepage.png
              href: https://gethomepage.dev/
              description: Homepage Documentation

  services.yaml: |
    - Operations:
        - NAS:
            href: https://nas.mcmumf.dev
            icon: mdi-nas
            description: Network Attached Storage

  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
