apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: networking
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: cloudflare-tunnel
            namespace: cloudflared
          - appName: dns
            namespace: dns
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: networking
      source:
        repoURL: https://github.com/McMumf/Homelab.git
        targetRevision: HEAD
        path: kubernetes/networking/{{appName}}
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 2
          backoff:
            duration: "5s"
            factor: 2
            maxDuration: "3m0s"
