---
- name: Restart k8s component
  shell: "kubeadm reset --force --cri-socket=unix:///var/run/crio/crio.sock"
  register: reset_cluster

- name: Init k8s cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --apiserver-advertise-address={{ IP_ADDR }} \
                 --apiserver-cert-extra-sans={{ IP_ADDR }} \
                 --node-name $(hostname -s) \
                 --pod-network-cidr {{ POD_NETWORK_CIDR }} \
                 --kubernetes-version {{ K8S_SEMANTIC_VERSION }} \
                 --cri-socket=unix:///var/run/crio/crio.sock
  register: init_cluster
  # See: https://github.com/jetstack/cert-manager/issues/2640 with using kubeadm + calico + cert-manager
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"

- name: Create k8s config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ KUBE_ADMIN_CONFIG }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

- name: Taint the master
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
