---
- name: Check if kubeadm has been ran
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init-cluster.yaml
  when: not kubeadm_ca.stat.exists
  run_once: true

- name: Enable and check kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: Copy config file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME')}}/admin.conf"
    flat: yes
  run_once: true
  ignore_errors: true
