apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: garage

helmGlobals:
  chartHome: ./helm

helmCharts:
  - name: garage
    releaseName: garage
    namespace: garage
    version: v1.2.0
    includeCRDs: true
    valuesFile: values.yaml
