apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-home

resources:
  - http-route.yaml
  - http-route-coder.yaml
  - service.yaml
  - service-coder.yaml
  - statefulset.yaml
