apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hassio
  namespace: smart-home
  labels:
    app: hassio
spec:
  serviceName: hassio
  replicas: 1
  selector:
    matchLabels:
      app: hassio
  template:
    metadata:
      labels:
        app: hassio
    spec:
      hostNetwork: false
      automountServiceAccountToken: false
      containers:
        - name: hassio
          image: "ghcr.io/home-assistant/home-assistant:2024.9.3"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
              ephemeral-storage: &ephemeralHaStorage 8Gi
            limits:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: *ephemeralHaStorage
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: hassio
              mountPath: /config
        - name: code-server
          image: codercom/code-server:4.93.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          resources:
            requests:
              memory: 1Gi
              cpu: 2000m
              ephemeral-storage: &ephemeralHaCodeStorage 8Gi
            limits:
              memory: 1Gi
              cpu: 2000m
              ephemeral-storage: *ephemeralHaStorage
          ports:
            - name: code-http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: hassio
              mountPath: /home/coder/hassio
            #   subPath: config
            # - name: hassio-code-server-data
            #   mountPath: /home/coder
      # initContainers:
      #   - name: code-server-init
      #     image: codercom/code-server:4.93.1
      #     imagePullPolicy: IfNotPresent
      #     command:
      #       - sh
      #       - -c
      #       - |
      #         code-server install-extension redhat.vscode-yaml
      #         code-server install-extension keesschollaart.vscode-home-assistant
      #     volumeMounts:
      #       - name: hassio-code-server-data
      #         mountPath: /home/coder
  volumeClaimTemplates:
    - metadata:
        name: hassio
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 32Gi
    - metadata:
        name: hassio-code-server-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 4Gi
