apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: apollo
  namespace: openebs
spec:
  node: apollo
  disks: [ "uring:///dev/disk/by-id/naa.500a07511ad63cec" ]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: artemis
  namespace: openebs
spec:
  node: artemis
  disks: [ "uring:///dev/disk/by-id/naa.500a07511ad6393d" ]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: skylab
  namespace: openebs
spec:
  node: skylab
  disks: [ "uring:///dev/disk/by-id/naa.500a07511ad725d0" ]
