openebs-crds:
  csi:
    volumeSnapshots:
      enabled: true
      keep: true

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false

localpv-provisioner:
  localpv:
    nodeSelector:
      openebs.io/engine: mayastor
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""

mayastor:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
  io_engine:
    envcontext: "iova-mode=pa"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
  etcd:
    nodeSelector:
      openebs.io/engine: mayastor
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
  loki-stack:
    enabled: false
    loki:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          value: ""
  csi:
    node:
      initContainers:
        # disable the init container that checks for the nvme_tcp module, since Talos has that module built-in.
        enabled: false

preUpgradeHook:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""

loki:
  enabled: true
