- name: ufw TCP rules
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "22" # SSH
    - "6443" # Kubernetes API Server
    - "10250" # kubelet API
    - "30000:32767" # Node Ports
    - "179" # Calico CNI
    - "4789" # Kubernetes networking plugin for overlay networking
    - "2379" # etcd datastore for communication between nodes

- name: ufw UDP rules
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "UDP"
  with_items:
    - "4789" # Kubernetes networking plugin for overlay networking
