apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: immich-postgres-secrets
  data:
    - secretKey: pg-username
      remoteRef:
        key: apps/immich
        property: postgres_user
    - secretKey: pg-password
      remoteRef:
        key: apps/immich
        property: postgres_password
