apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-backup
  namespace: velero
spec:
  # Run Weekly
  schedule: "0 2 * * 0"
  template:
    # Keep for 21 days
    ttl: 504h
    # Include all namespaces
    includedNamespaces:
      - "*"
    # Exclude velero namespace
    excludedNamespaces:
      - velero
      - openebs
      - kube-system
    includeClusterResources: true
    storageLocation: backblaze
    volumeSnapshotLocations:
      - default-vsl
    snapshotVolumes: true
    resourcePolicy:
      kind: configmap
      name: velero-anti-nfs-policy
    # Add labels to track scheduled backups
    metadata:
      labels:
        schedule: daily
        type: full
