snapshotsEnabled: false

deployNodeAgent: true
nodeAgent:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

credentials:
  useSecret: true
  existingSecret: velero-s3-creds

kubectl:
  image:
    tag: "1.35.1"

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: plugins
        mountPath: /target

configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
    - name: backblaze
      provider: aws
      bucket: mumf-homelab-backups
      default: true
      config:
        region: us-east-005
        s3ForcePathStyle: "true"
        s3Url: https://s3.us-east-005.backblazeb2.com
  volumeSnapshotLocation: []

extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: velero-s3-creds
      namespace: velero
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: backups-secret-store
        kind: ClusterSecretStore
      target:
        name: velero-s3-creds
      data:
        - secretKey: cloud
          remoteRef:
            key: backups/backblaze
            property: bucket-credentials
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: velero-anti-nfs-policy
      namespace: velero
      labels:
        velero.io/plugin-config: "true"
        velero.io/resource-policy: "true"
    data:
      policy.yaml: |
        version: v1
        volumePolicies:
          # Don't backup NFS
          - conditions:
              nfs: {}
            action:
              type: skip
          - conditions:
              volumeTypes:
                - hostPath
            action:
              type: skip

# Velero server resources
resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi
