apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: n8n-worker
    app.kubernetes.io/part-of: n8n
    app.kubernetes.io/version: 2.11.4
    helm.sh/chart: n8n-1.16.31
  name: n8n-worker
  namespace: n8n
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: n8n
      app.kubernetes.io/name: n8n-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: ba6ae0afb7c6c5258480ccc547c812e0bbf2b36213cbcff248dedbdaaf2867f4
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: n8n
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: n8n-worker
        app.kubernetes.io/part-of: n8n
        app.kubernetes.io/version: 2.11.4
        helm.sh/chart: n8n-1.16.31
    spec:
      containers:
        - args:
            - worker
            - --concurrency=10
          command:
            - n8n
          env:
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: NODE_ENV
              value: production
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_DEFAULT_LOCALE
              value: en
            - name: GENERIC_TIMEZONE
              value: America/New_York
            - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
              value: "30"
            - name: N8N_DISABLE_UI
              value: "true"
            - name: QUEUE_HEALTH_CHECK_ACTIVE
              value: "true"
            - name: N8N_CONCURRENCY_PRODUCTION_LIMIT
              value: "10"
            - name: DB_POSTGRESDB_USER
              value: n8n
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: n8n-cnpg-app
                  optional: true
            - name: QUEUE_BULL_REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: redis-username
                  name: n8n-redis
                  optional: true
            - name: QUEUE_BULL_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: n8n-redis
                  optional: true
          envFrom:
            - configMapRef:
                name: n8n-database-configmap
            - configMapRef:
                name: n8n-logging-configmap
            - configMapRef:
                name: n8n-diagnostics-configmap
            - configMapRef:
                name: n8n-version-notifications-configmap
            - configMapRef:
                name: n8n-public-api-configmap
            - configMapRef:
                name: n8n-queue-configmap
            - configMapRef:
                name: n8n-task-broker-configmap
            - configMapRef:
                name: n8n-metrics-configmap
            - configMapRef:
                name: n8n-binary-data-configmap
            - secretRef:
                name: n8n-encryption-key-secret-v2
          image: n8nio/n8n:2.13.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          name: n8n-worker
          ports:
            - containerPort: 5678
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: http
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep '[n]8n'
            failureThreshold: 30
            initialDelaySeconds: 10
            periodSeconds: 5
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccountName: n8n
