apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

helmCharts:
  - name: monitoring
    repo: https://openebs.github.io/monitoring/
    releaseName: monitoring
    namespace: openebs
    version: 4.1.1
    includeCRDs: true
    valuesFile: values.yaml
