apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantit-db
  namespace: apps
  labels:
    app: plantit-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantit-db
  template:
    metadata:
      labels:
        app: plantit-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plantitsecret
                  key: MYSQL_ROOT_PASSWORD
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: plantit-db-pv-claim
