apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plantit-db-pv-claim
  namespace: apps
spec:
  storageClassName: openebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
