apiVersion: v1
kind: Service
metadata:
  name: minecraft-router-game
  namespace: games
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.10
  selector:
    app: minecraft-router
  ports:
    - name: minecraft-router-game
      protocol: TCP
      port: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-router-api
  namespace: games
spec:
  selector:
    app: minecraft-router
  ports:
    - name: minecraft-router-api
      protocol: TCP
      port: 8080
