apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - l2-advertisement.yaml
  - ip-addr-pool.yaml
  - namespace.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb
    namespace: metallb-system
    version: 0.15.1
    valuesFile: values.yaml
