apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: atlantis
    - matchLabels:
        kubernetes.io/hostname: columbia
    - matchLabels:
        kubernetes.io/hostname: challenger
