apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: apiKey
      remoteRef:
        key: infrastructure/cert-manager
        property: cloudflare-api-token
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
