apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
  data:
    - secretKey: secret_key
      remoteRef:
        key: apps/paperless
        property: secret_key

    - secretKey: admin_user
      remoteRef:
        key: apps/paperless
        property: admin_user

    - secretKey: admin_email
      remoteRef:
        key: apps/paperless
        property: admin_email

    - secretKey: admin_password
      remoteRef:
        key: apps/paperless
        property: admin_password
