apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
  data:
    - secretKey: secret_key
      remoteRef:
        key: kv/paperless
        property: secret_key
    - secretKey: admin_user
      remoteRef:
        key: kv/paperless
        property: admin_user
    - secretKey: admin_email
      remoteRef:
        key: kv/paperless
        property: admin_email
    - secretKey: admin_password
      remoteRef:
        key: kv/paperless
        property: admin_password
