apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
  data:
    - secretKey: secret_key
      remoteRef:
        key: kv/paperless
        property: secret_key
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: admin_user
      remoteRef:
        key: kv/paperless
        property: admin_user
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: admin_email
      remoteRef:
        key: kv/paperless
        property: admin_email
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: admin_password
      remoteRef:
        key: kv/paperless
        property: admin_password
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

