---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-vanilla
  namespace: games
  annotations:
    "mc-router.itzg.me/externalServerName": "mc.mcmumf.dev"
spec:
  selector:
    app: minecraft-vanilla
  ports:
    - name: minecraft-vanilla
      protocol: TCP
      port: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-router-bedrock
  namespace: games
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.5.11
  selector:
    app: minecraft-vanilla
  ports:
    - name: minecraft-bedrock
      protocol: TCP
      port: 19132
    - name: minecraft-bedrock-udp
      protocol: UDP
      port: 19132
