server:
  ingress:
    enabled: false
    host: example.com
    tls:
      enabled: false
    certManager:
      enabled: false
      issuer: letsencrypt

machine-learning:

postgres:

redis:

secrets:
  vault:
    enabled: false
