persistence:
  enabled: true
  size: 50Gi

config:
  publicURI: "https://penpot.mcmumf.dev"
  flags: "enable-registration enable-login disable-demo-users disable-demo-warning enable-smtp enable-login-with-google"
  apiSecretKey: <REDACTED>

  # postgresql:
  #   host: "postgresql.postgresql.svc.cluster.local"
  #   port: 5432
  #   database: penpot
  #   existingSecret: "penpot-config-secret"
  #   secretKeys:
  #     usernameKey: "postgresql-username"
  #     passwordKey: "postgresql-password"

  # redis:
  #   host: "redis-headless.redis.svc.cluster.local"
  #   port: 6379
  #   database: "0"

  smtp:
    enabled: true
    defaultFrom: "penpot@mcmumf.dev"
    defaultReplyTo: "design@example.com"
    host: "smtp.gmail.com"
    port: "587"
    tls: true
    existingSecret: "penpot-config-secret"
    secretKeys:
      usernameKey: "smtp-username"
      passwordKey: "smtp-password"

  registrationDomainWhitelist: "mcmumf.dev"

  providers:
    google:
      enabled: true

    existingSecret: "penpot-config-secret"
    secretKeys:
      googleClientIDKey: "google-client-id"
      googleClientSecretKey: "google-client-secret"
