repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: vault
    namespace: secrets-management
    createNamespace: true
    chart: hashicorp/vault
    version: 0.28.1
    values:
      - includeCRDs: true
