repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    values:
    - installCRDs: true
  - name: vault
    namespace: secrets-management
    createNamespace: true
    chart: hashicorp/vault
    version: 0.27.0
    values:
      - includeCRDs: true
