repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: vault
    namespace: infrastructure
    createNamespace: true
    chart: hashicorp/vault
    version: 0.27.0
    values:
      - values.yaml
