apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.28.1
    releaseName: vault
    namespace: vault
    includeCRDs: true
    valuesInline:
      includeCRDs: true
