apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

# resources:
#   - external-secrets.yaml

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg-operator
    namespace: media
    version: 0.1.3
    valuesFile: values.yaml
