apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hortusfox-secrets
  namespace: homelab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hortusfox-secrets
  data:
    - secretKey: mariadb-root-password
      remoteRef:
        key: kv/hortusfox
        property: mariadb-password

    - secretKey: mariadb-replication-password
      remoteRef:
        key: kv/hortusfox
        property: mariadb-password

    - secretKey: mariadb-password
      remoteRef:
        key: kv/hortusfox
        property: mariadb-password
