apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adventurelog-secrets
  namespace: adventure
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: adventurelog-secret
  data:
    - secretKey: adventure-postgres-password
      remoteRef:
        key: apps/adventurelog
        property: pg-password

    - secretKey: admin-email
      remoteRef:
        key: apps/adventurelog
        property: admin-email

    - secretKey: admin-username
      remoteRef:
        key: apps/adventurelog
        property: admin-username

    - secretKey: admin-password
      remoteRef:
        key: apps/adventurelog
        property: admin-password
