apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "home-assistant.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralStorage }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralStorage }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: zigbee
              mountPath: /dev/ttyUSB0
            # - name: serial
            #   mountPath: /dev/serial/by-id
            - name: {{ include "home-assistant.fullname" . }}
              mountPath: /config
            - name: {{ include "home-assistant.fullname" . }}-config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: {{ include "home-assistant.fullname" . }}-config
              mountPath: /config/automations.yaml
              subPath: automations.yaml
            - name: {{ include "home-assistant.fullname" . }}-config
              mountPath: /config/scenes.yaml
              subPath: scenes.yaml
            - name: {{ include "home-assistant.fullname" . }}-config
              mountPath: /config/scripts.yaml
              subPath: scripts.yaml
      volumes:
        - name: zigbee
          hostPath:
            path: /dev/ttyUSB0
        # - name: serial
        #   hostPath:
        #     path: /dev/serial/by-id
        - name: {{ include "home-assistant.fullname" . }}-config
          configMap:
            name: {{ include "home-assistant.fullname" . }}-config
            items:
              - key: configuration.yaml
                path: configuration.yaml
              - key: automations.yaml
                path: automations.yaml
              - key: scenes.yaml
                path: scenes.yaml
              - key: scripts.yaml
                path: scripts.yaml
  volumeClaimTemplates:
    - metadata:
        name: {{ include "home-assistant.fullname" . }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
