apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: apps
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: apps-secret-store
    kind: ClusterSecretStore
  target:
    name: mealie-secrets
  data:
    - secretKey: smtp-user
      remoteRef:
        key: apps/recipes
        property: smtp-username

    - secretKey: smtp-password
      remoteRef:
        key: apps/recipes
        property: smtp-token

    - secretKey: smtp-server
      remoteRef:
        key: apps/recipes
        property: smtp-server

    - secretKey: client-id
      remoteRef:
        key: apps/recipes
        property: client-id

    - secretKey: client-secret
      remoteRef:
        key: apps/recipes
        property: client-secret
