apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mealie-secrets
  data:
    - secretKey: smtp-user
      remoteRef:
        key: kv/recipes
        property: smtp-username

    - secretKey: smtp-password
      remoteRef:
        key: kv/recipes
        property: smtp-token

    - secretKey: smtp-server
      remoteRef:
        key: kv/recipes
        property: smtp-server
