apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-secrets
  namespace: homelab
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mealie-secrets
  data:
    - secretKey: smtp-user
      remoteRef:
        key: kv/recipes
        property: smtp-username
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: smtp-password
      remoteRef:
        key: kv/recipes
        property: smtp-token
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue

    - secretKey: smtp-server
      remoteRef:
        key: kv/recipes
        property: smtp-server
        conversionStrategy: Default # ArgoCD sync issue
        decodingStrategy: None # ArgoCD sync issue
        metadataPolicy: None # ArgoCD sync issue
