apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mealie
  namespace: apps
spec:
  selector:
    matchLabels:
      app: mealie
  serviceName: "mealie"
  replicas: 1
  template:
    metadata:
      labels:
        app: mealie
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mealie
          image: hkotel/mealie:v2.3.0
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: 8Gi
            limits:
              memory: 8Gi
              cpu: 2000m
              ephemeral-storage: 8Gi
          env:
            # General Configs
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: BASE_URL
              value: "https://recipes.mcmumf.dev"
            - name: TOKEN_TIME
              value: "24"
            - name: TZ
              value: "UTC"
            - name: ALLOW_SIGNUP
              value: "False"
            # Security Configs
            - name: SECURITY_MAX_LOGIN_ATTEMPTS
              value: "5"
            - name: SECURITY_USER_LOCKOUT_TIME
              value: "24"
            # OIDC Configs
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_SIGNUP_ENABLED
              value: "true"
            - name: OIDC_CONFIGURATION_URL
              value: "https://auth.mcmumf.dev/application/o/recipes/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: client-id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: client-secret
            - name: OIDC_PROVIDER_NAME
              value: "auth.mcmumf.dev"
            - name: OIDC_AUTO_REDIRECT
              value: "false"
            - name: OIDC_REMEMBER_ME
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: OIDC_USER_CLAIM
              value: "email"
            - name: OIDC_USER_GROUP
              value: "HomelabUsers"
            - name: OIDC_ADMIN_GROUP
              value: "RecipeAdmin"
            # SMTP Config
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-server
            - name: SMPT_PORT
              value: "587"
            - name: SMTP_FROM_NAME
              value: Mealie
            - name: SMTP_AUTH_STRATEGY
              value: TLS
            - name: SMTP_FROM_EMAIL
              value: recipes@mcmumf.dev
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-password
            # Web Worker Configs
            - name: MAX_WORKERS
              value: "10"
            - name: WEB_CONCURRENCY
              value: "2"
            # Database Settings
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cnpg-apps-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-apps-app
                  key: password
            - name: POSTGRES_SERVER
              value: cnpg-apps-rw.apps
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: app
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: mealie-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 8Gi
