apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mealie
  namespace: homelab
spec:
  selector:
    matchLabels:
      app: mealie
  serviceName: "mealie"
  replicas: 1
  template:
    metadata:
      labels:
        app: mealie
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mealie
          image: hkotel/mealie:v2.3.0
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
              ephemeral-storage: 8Gi
            limits:
              memory: 8Gi
              cpu: 2000m
              ephemeral-storage: 8Gi
          env:
            # General Configs
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: BASE_URL
              value: "https://recipes.mcmumf.dev"
            - name: TOKEN_TIME
              value: "24"
            - name: TZ
              value: "UTC"
            - name: ALLOW_SIGNUP
              value: "False"
            # Security Configs
            - name: SECURITY_MAX_LOGIN_ATTEMPTS
              value: "5"
            - name: SECURITY_USER_LOCKOUT_TIME
              value: "24"
            # LDAP Configs
            # - name: LDAP_AUTH_ENABLED
            #   value: "True"
            # - name: LDAP_SERVER_URL
            #   value: "ldap://ldap.mcmumf.dev"
            # - name: LDAP_BIND_TEMPLATE
            #   value: "cn={},ou=users,dc=mcmumf,dc=dev"
            # SMTP Config
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-server
            - name: SMPT_PORT
              value: "587"
            - name: SMTP_FROM_NAME
              value: Mealie
            - name: SMTP_AUTH_STRATEGY
              value: TLS
            - name: SMTP_FROM_EMAIL
              value: recipes@mcmumf.dev
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: smtp-password
            # Web Worker Configs
            - name: MAX_WORKERS
              value: "10"
            - name: WEB_CONCURRENCY
              value: "2"
            # Database Settings
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_USER
              value: mealie
            - name: POSTGRES_PASSWORD
              value: mealie
            - name: POSTGRES_SERVER
              value: postgres-postgresql.storage.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: mealie
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: mealie-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 8Gi
