apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
   # Helm Chart
    - repoURL: "https://charts.goauthentik.io"
      targetRevision: "2025.4.0"
      chart: authentik
      helm:
        valueFiles:
          - $values/kubernetes/infrastructure/authentik/values.yaml
    # Helm Values
    - repoURL: "https://github.com/McMumf/homelab"
      targetRevision: "talos"
      ref: values
    # Kustomize
    - repoURL: 'https://github.com/McMumf/homelab'
      targetRevision: 'talos'
      path: kubernetes/infrastructure/authentik
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
