apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infra-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: infra/authentik
        property: postgresql_password

    - secretKey: postgres-password
      remoteRef:
        key: infra/authentik
        property: postgresql_password

    - secretKey: password
      remoteRef:
        key: infra/authentik
        property: postgresql_password

    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: infra/authentik
        property: secret_key

    - secretKey: AUTHENTIK_EMAIL__HOST
      remoteRef:
        key: infra/authentik
        property: email_host

    - secretKey: AUTHENTIK_EMAIL__FROM
      remoteRef:
        key: infra/authentik
        property: email_user

    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: infra/authentik
        property: email_user

    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: infra/authentik
        property: email_password
