apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: kv/authentik
        property: postgresql_password

    - secretKey: postgres-password
      remoteRef:
        key: kv/authentik
        property: postgresql_password
    
    - secretKey: password
      remoteRef:
        key: kv/authentik
        property: postgresql_password

    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: kv/authentik
        property: secret_key

    - secretKey: AUTHENTIK_EMAIL__USERNAME
      remoteRef:
        key: kv/authentik
        property: email_access_key

    - secretKey: AUTHENTIK_EMAIL__PASSWORD
      remoteRef:
        key: kv/authentik
        property: email_secret_key
