repositories:
  - name: authentik
    url: https://charts.goauthentik.io

releases:
  - name: authentik
    namespace: authentik
    createNamespace: true
    chart: authentik/authentik
    version: 2024.10.1
    values:
      - values.yaml
