apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets.yaml

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    releaseName: authentik
    namespace: authentik
    version: 2024.8.3
    valuesFile: values.yaml
