authentik:
  error_reporting:
    enabled: true
  log_level: trace
  email:
    use_tls: true

global:
  postgresql:
    enabled: true
    auth:
      existingSecret: authentik-secrets
  envFrom:
    - secretRef:
        name: authentik-secrets

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-secrets

redis:
  enabled: true

server:
  volumes:
    - name: tls-cert
      secret:
        secretName: authentik-cert
  volumeMounts:
    - name: tls-cert
      mountPath: /certs
      readOnly: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/server-snippet: |
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "Upgrade";
    hosts:
      - &authentikHost auth.mcmumf.dev
    tls:
      - hosts:
          - *authentikHost
        secretName: authentik-cert

worker:
  volumes:
    - name: tls-cert
      secret:
        secretName: authentik-cert
  volumeMounts:
    - name: tls-cert
      mountPath: /certs
      readOnly: true
