apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kasten-io

helmCharts:
  - name: k10
    repo: https://charts.kasten.io/
    releaseName: k10
    namespace: kasten-io
    version: 7.5.10
    valuesFile: values.yaml
