apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: smart-home
  labels:
    app: zigbee2mqtt
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/description: Manage zigbee devices
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Operations
    gethomepage.dev/icon: https://raw.githubusercontent.com/Koenkk/zigbee2mqtt/refs/heads/master/images/logo.png
    gethomepage.dev/name: Zigbee2MQTT
    gethomepage.dev/pod-selector: "app=zigbee2mqtt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - &hostName z2m.mcmumf.dev
      secretName: z2m.mcmumf.dev-tls
  rules:
    - host: *hostName
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
