apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-home

helmCharts:
  - name: zigbee2mqtt
    repo: https://charts.zigbee2mqtt.io
    releaseName: zigbee2mqtt
    namespace: smart-home
    version: 2.6.2
    valuesFile: values.yaml
