apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tigera-operator

helmCharts:
  - name: tigera-operator
    repo: https://docs.tigera.io/calico/charts
    releaseName: calico
    namespace: tigera-operator
    version: v3.29.0
    valuesFile: values.yaml
