apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data
  namespace: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs
  resources:
    requests:
      storage: 32Gi
