apiVersion: v1
kind: ServiceAccount
metadata:
  name: outline-svc-acct
  namespace: outline
  labels:
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
automountServiceAccountToken: true
