- name: Install CRI-O
  include_tasks: pkg.yml

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start the crio service
  become: true
  ansible.builtin.systemd:
    name: crio
    enabled: true
    state: started
