apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg-operator
    namespace: cnpg-system
    version: 0.23.0
    valuesFile: values.yaml
