- name: Reset k8s
  become: true
  shell: |
    kubeadm reset

- name: Purge apt things
  become: true
  shell: |
    apt purge kubectl kubeadm kubelet kubernetes-cni cri-o -y --allow-change-held-packages

- name: apt autoremove
  become: true
  shell: |
    apt autoremove

- name: Remove k8s folders
  become: true
  shell: |
    rm -rf /etc/cni /etc/kubernetes /var/lib/dockershim /var/lib/etcd /var/lib/kubelet /var/run/kubernetes ~/.kube/*

- name: reset iptables
  become: true
  shell: |
    iptables -F && sudo iptables -t nat -F && sudo iptables -t mangle -F && sudo iptables -X

- name: remove sources
  become: true
  shell: |
    rm /etc/apt/sources.list.d/cri-o.list && rm /etc/apt/sources.list.d/kubernetes.list
