apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:7.4-alpine@sha256:de13e74e14b98eb96bdf886791ae47686c3c5d29f9d5f85ea55206843e3fce26
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 5Gi
          ports:
          - containerPort: 6379
      restartPolicy: Always
