apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-redis
spec:
  type: ClusterIP
  selector:
    app: immich-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
