apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: immich-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:7.4-alpine@sha256:dd6c86dc8f3be0526b2baa964473e2443b5a4412c4c2232781ca9820296d407b
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 5Gi
          ports:
          - containerPort: 6379
      restartPolicy: Always
