apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plant-it
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/McMumf/homelab"
      targetRevision: "talos"
      path: kubernetes/applications/plant-it
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
