apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: outline-backup
spec:
  schedule: "0 0 1 * * *" # At 0100 every day
  method: volumeSnapshot
  backupOwnerReference: cluster
  cluster:
    name: outline-cnpg
