#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  external_url: {{ .Values.configMap.externalUrl }}
  time_zone: America/New_York

# Loads default set of integrations. Do not remove.
default_config:
{{ if .Values.configMap.proxy.enabled }}
http:
  use_x_forwarded_for: true
  trusted_proxies:
  {{- range $v := .Values.configMap.proxy.trustedProxies }}
    - {{ $v }}
  {{- end }}
{{ end }}

#################################################################
## Includes
#################################################################

automation ui: !include automations.yaml


