repositories:
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts

releases:
  - name: cloudflared
    namespace: cloudflared
    createNamespace: true
    chart: cloudflare/cloudflare-tunnel
    version: 0.3.2
    values:
      - values.yaml
