cloudflare:
  tunnelName: "k8s-tunnel"
  # Secret defines the tunnelId, tunnelName, accountNumber, and tunnel secret
  secretName: tunnel-credentials
  # Define ingress rules for the tunnel. See
  # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/configuration-file/ingress
  originRequest:
    http2Origin: true # Attempts to use HTTP/2.0
  ingress:
    - hostname: "*.mcmumf.dev"
      service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      originRequest:
        originServerName: mcmumf.dev
    - hostname: "mc.mcmumf.dev"
      service: http://minecraft-vanilla-lb.games.svc.cluster.local:25565
      originRequest:
        originServerName: mc.mcmumf.dev
